# The recommended basic settings for GNN
out_dir: results
dataset:
  format: PyG
  name: Cora
  task: node
  task_type: classification
  transductive: True
  split: [0.6, 0.2, 0.2]
  transform: none
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: localWL
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_post_mp: 2
  dim_inner: 128
  layer_type: generalconv
  stage_type: stack
  batchnorm: True
  act: prelu
  dropout: 0.0
  agg: add
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 400
localWL:
  hops: 3
  pool: sum
  dropout: 0.9
  walk: dfs
  sortBy: None
  reverse: False
  beamSize: None
  maxPathLen: 3

