# The recommended basic settings for GNN
out_dir: results
num_threads: 8
num_workers: 1
dataset:
  format: OGB
  name: ogbg-molhiv
  task: graph
  task_type: classification
  transductive: True
  transform: none
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: localWL
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_post_mp: 1
  layers_mp: 2
  dim_inner: 64
  layer_type: generalconv
  stage_type: stack
  batchnorm: True
  act: prelu
  dropout: 0.5
  agg: add
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 200
localWL:
  hops: 1
  pool: sum
  dropout: 0.8
  walk: dfs
  sortBy: None
  reverse: False
  beamSize: None
  maxPathLen: 8
  mlp_layer: 3
  hop_pool: sum

